# Scalars, Vectors, and Matrices
---
**Author:** Hamna Munir  
**Repository:** Math-for-Machine-Learning  
**Notebook:** 01-scalars-vectors-matrices.ipynb

**Goal:** Understand the basic mathematical objects used in Machine Learning and how they are represented using Python and NumPy.
---

## Concept
Scalars, vectors, and matrices are the fundamental mathematical structures used to represent data and parameters in Machine Learning models.

## Mathematical Explanation
- A scalar is a single numerical value.
- A vector is an ordered collection of numbers, typically representing features.
- A matrix is a two-dimensional collection of numbers used to represent datasets or transformations.

These structures allow Machine Learning algorithms to process data efficiently and mathematically.

### Scalars

In [1]:
scalar = 5
scalar

5

### Vectors

In [2]:
import numpy as np

vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

### Matrices

In [3]:
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

## Visualization
Visualizing a vector as a simple line plot helps in understanding its structure.

In [4]:
import matplotlib.pyplot as plt

x = np.array([0, 1, 2])
y = np.array([1, 2, 3])

plt.plot(x, y, marker='o')
plt.xlabel('Index')
plt.ylabel('Value')
plt.title('Vector Visualization')
plt.show()

## Python Code
NumPy provides efficient data structures to perform mathematical operations on vectors and matrices.

In [5]:
matrix + 1

array([[2, 3],
       [4, 5]])

## ML Connection
In Machine Learning, scalars represent parameters such as learning rates, vectors represent feature inputs, and matrices represent datasets and weight matrices used in model computations.

## Summary
- Scalars are single numerical values
- Vectors represent ordered data or features
- Matrices represent structured datasets
- These concepts form the foundation of all Machine Learning algorithms

Developed by **Hamna Munir**
---