# Matrix Operations
---
**Author:** Hamna Munir  
**Repository:** Math-for-Machine-Learning  
**Notebook:** 03-matrix-operations.ipynb

**Goal:** Understand matrix operations and their importance in Machine Learning.
---

## Concept
Matrices are two-dimensional arrays of numbers used to represent datasets, transformations, and relationships between multiple variables. Matrix operations form the backbone of Machine Learning algorithms.

## Mathematical Explanation
Common matrix operations include addition, subtraction, scalar multiplication, matrix multiplication, transpose, and determinant. These operations are essential for linear transformations, system solving, and optimization.

### Matrix Creation

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

A, B

(array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]))

### Basic Matrix Operations

In [2]:
A + B, B - A, A * 2

(array([[ 6,  8],
       [10, 12]]), array([[4, 4],
       [4, 4]]), array([[2, 4],
       [6, 8]]))

### Matrix Multiplication

In [3]:
A @ B

array([[19, 22],
       [43, 50]])

### Matrix Transpose

In [4]:
A.T

array([[1, 3],
       [2, 4]])

### Determinant

In [5]:
np.linalg.det(A)

-2.0000000000000004

## Visualization
Heatmaps provide an intuitive way to understand matrix values and structure.

In [6]:
import matplotlib.pyplot as plt

plt.imshow(A, cmap='viridis')
plt.colorbar()
plt.title('Matrix Heatmap')
plt.show()

## ML Connection
Matrices represent datasets, weight parameters, and transformations in Machine Learning. Matrix multiplication is central to neural networks, linear regression, and dimensionality reduction techniques.

## Summary
- Matrices organize multi-dimensional data
- Matrix multiplication enables feature transformation
- Transpose and determinant are essential for optimization and stability analysis

Developed by **Hamna Munir**
---