# Singular Value Decomposition (SVD)
---
**Author:** Hamna Munir  
**Repository:** Math-for-Machine-Learning  
**Notebook:** 13-singular-value-decomposition.ipynb

**Goal:** Understand Singular Value Decomposition and its applications in Machine Learning.
---

## Concept
Singular Value Decomposition (SVD) factorizes any matrix into three components that reveal its geometric and structural properties.

## Mathematical Explanation
For any matrix A ∈ ℝᵐˣⁿ:

A = U Σ Vᵀ

Where:
- U is an orthogonal matrix (left singular vectors)
- Σ is a diagonal matrix of singular values
- Vᵀ is the transpose of an orthogonal matrix (right singular vectors)

Properties:
- Singular values are non-negative
- Rank equals number of non-zero singular values
- Works for non-square matrices
- More stable than eigen-decomposition

## Python Code
Compute SVD using NumPy.

In [1]:
import numpy as np

A = np.array([[3, 1],
              [1, 3]])

U, S, Vt = np.linalg.svd(A)

U, S, Vt

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [-0.81741556,  0.57604844]]))

## Matrix Reconstruction
Reconstruct A using U, Σ, and Vᵀ.

In [2]:
Sigma = np.diag(S)

A_reconstructed = U @ Sigma @ Vt
A_reconstructed

array([[3., 1.],
       [1., 3.]])

## Low-Rank Approximation
Approximate A using top singular values.

In [3]:
k = 1

U_k = U[:, :k]
S_k = np.diag(S[:k])
Vt_k = Vt[:k, :]

A_approx = U_k @ S_k @ Vt_k
A_approx

array([[2.9294472 , 1.04668421],
       [1.04668421, 2.53553851]])

## Visualization
Singular values show importance of components.

In [4]:
import matplotlib.pyplot as plt

plt.plot(S, marker='o')
plt.title("Singular Values")
plt.xlabel("Index")
plt.ylabel("Value")
plt.grid()
plt.show()

## ML Connection
SVD is used in:
- Principal Component Analysis (PCA)
- Dimensionality reduction
- Noise filtering
- Recommendation systems
- Image compression
- Latent Semantic Analysis (NLP)

## Summary
- SVD decomposes A into U Σ Vᵀ
- Works for any matrix
- Enables low-rank approximation
- Essential for PCA and compression
- Improves efficiency in ML models

Developed by **Hamna Munir**
---