# Linear Algebra in Machine Learning
---
**Author:** Hamna Munir  
**Repository:** Math-for-Machine-Learning  
**Notebook:** 15-linear-algebra-in-ml.ipynb

**Goal:** Understand how linear algebra concepts are used in real Machine Learning algorithms.
---

## Concept
Linear algebra provides the mathematical foundation for representing data, training models, and optimizing learning algorithms.

## Mathematical Explanation
Key concepts used in ML:

- Vectors: represent data samples
- Matrices: represent datasets and parameters
- Dot products: measure similarity
- Eigenvalues: dimensionality reduction
- SVD: matrix factorization
- Projections: least squares
- Norms: regularization
- Rank: information content

Most ML models can be written as matrix equations.

## Representing Data as Matrices
Convert dataset into matrix form.

In [1]:
import numpy as np

# Feature matrix
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5]
])

X

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

## Linear Regression Using Matrices
Normal equation solution.

In [2]:
y = np.array([3, 5, 7, 9])

# Add bias term
X_b = np.c_[np.ones((X.shape[0], 1)), X]

# Normal equation
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

theta

array([0.5, 1. ])

## Similarity Using Dot Product
Cosine similarity measures closeness of vectors.

In [3]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])

cosine_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosine_sim

0.9922778767136677

## PCA Using SVD
Dimensionality reduction with matrix factorization.

In [4]:
# Center data
X_centered = X - X.mean(axis=0)

U, S, Vt = np.linalg.svd(X_centered)

# First principal component
X_reduced = U[:, :1] * S[:1]

X_reduced

array([[ 2.12132034],
       [ 0.        ],
       [-2.12132034],
       [ 0.        ]])

## Regularization Using Norms
Prevent overfitting with L2 regularization.

In [5]:
weights = np.array([0.5, 1.0])

l2_norm = np.linalg.norm(weights)
l2_norm

1.118033988749895

## ML Connection
Linear algebra powers:
- Neural networks (matrix multiplications)
- Regression models
- PCA and clustering
- Recommendation systems
- NLP embeddings
- Computer vision pipelines

## Summary
- Data is stored as matrices
- Models use matrix equations
- SVD enables PCA
- Norms control overfitting
- Similarity uses dot products
- Linear algebra is core to ML

Developed by **Hamna Munir**
---