# NumPy Basics for Mathematical Computing
---
**Author:** Hamna Munir  
**Repository:** Math-for-Machine-Learning  
**Notebook:** 02-numpy-basics.ipynb

**Goal:** Learn NumPy fundamentals required for efficient mathematical operations in Machine Learning.
---

##  Concept
NumPy (Numerical Python) is a core Python library used for numerical and mathematical computations. It provides powerful data structures such as arrays that enable fast and efficient operations required in Machine Learning.

##  Mathematical Explanation
Machine Learning relies on vectors, matrices, and numerical transformations. NumPy represents these mathematical objects as arrays and performs operations using optimized low-level implementations, making computations faster and more reliable.

### Creating NumPy Arrays

In [1]:
import numpy as np

one_d = np.array([1, 2, 3, 4, 5])
two_d = np.array([[1, 2, 3], [4, 5, 6]])

print(one_d)
print(two_d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


##  Visualization
Visualizing array-based computations helps build intuition for how data is transformed mathematically.

In [2]:
import matplotlib.pyplot as plt

x = np.arange(0, 10)
y = x ** 2

plt.plot(x, y, marker='o')
plt.xlabel('x')
plt.ylabel('x squared')
plt.title('NumPy Array Computation: y = x²')
plt.show()

##  Python Code
NumPy supports vectorized operations, allowing mathematical expressions to be applied to entire arrays at once.

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr * 2

array([ 2,  4,  6,  8, 10])

##  ML Connection
NumPy arrays are the foundation of Machine Learning. They are used to store datasets, perform matrix multiplications, compute gradients, and implement optimization algorithms efficiently.

##  Summary
- NumPy enables fast and efficient numerical computation
- Arrays represent vectors and matrices used in ML
- Vectorized operations simplify mathematical code
- NumPy is essential for data science and Machine Learning

Developed by — Hamna Munir 
---